
local wshop = require("libs_powered").NewWShop("DFHACK_POWERED_TELEPORTER", "Powered Teleporter")
wshop.ExtraItems = [[
	[BUILD_ITEM:10:TOOL:ITEM_TOOL_TELEPORTER_COIL:INORGANIC:NONE]
		[CAN_USE_ARTIFACT]
	[BUILD_ITEM:4:TOOL:ITEM_TOOL_TELEPORTER_POLE:INORGANIC:NONE]
		[CAN_USE_ARTIFACT]
	[BUILD_ITEM:4:TOOL:ITEM_TOOL_TELEPORTER_SPHERE:INORGANIC:NONE]
		[CAN_USE_ARTIFACT]
	[BUILD_ITEM:2:TOOL:ITEM_TOOL_TELEPORTER_CLOCKWORK:INORGANIC:NONE]
		[CAN_USE_ARTIFACT]
]]
