
local wshop = require("libs_powered").NewWShop("DFHACK_POWERED_DRILLING_RIG", "Powered Drilling Rig")
wshop.ExtraItems = [[
	[BUILD_ITEM:2:TRAPCOMP:ITEM_TRAPCOMP_MECHANICAL_ARM:NONE:NONE]
		[CAN_USE_ARTIFACT]
	[BUILD_ITEM:1:TRAPCOMP:DFHACK_POWERED_DRILLING_RIG_BIT:NONE:NONE]
		[CAN_USE_ARTIFACT]
]]
