
local wshop = require("libs_powered").NewWShop("DFHACK_POWERED_SAWMILL", "Powered Sawmill")
wshop.ExtraItems = [[
	[BUILD_ITEM:1:TRAPCOMP:ITEM_TRAPCOMP_LARGESERRATEDDISC:NONE:NONE]
		[CAN_USE_ARTIFACT]
	[BUILD_ITEM:2:TRAPCOMP:ITEM_TRAPCOMP_MECHANICAL_ARM:NONE:NONE]
		[CAN_USE_ARTIFACT]
]]
