
local wshop = require("libs_powered").NewWShop("DFHACK_POWERED_CATAPULT",  "Powered Catapult")
wshop.ExtraItems = [[
	[BUILD_ITEM:2:TRAPCOMP:ITEM_TRAPCOMP_MECHANICAL_ARM:NONE:NONE]
		[CAN_USE_ARTIFACT]
	[BUILD_ITEM:3:CATAPULTPARTS:NONE:NONE:NONE]
		[CAN_USE_ARTIFACT]
]]
